### ISSUE TITLE
Add Brew Formulae

### ISSUE THREAD

**Issue by danulqua** [microsoft/inshellisense#82] opened 2023-11-16 10:00 UTC
**Is your feature request related to a problem? Please describe.**
Currently, we can install **Inshellisense** via **npm**. The issue is if user uses node version manager which is not unusual in real development life, he encounters the package disappearing and need to install it again.

**Describe the solution you'd like**
Add the **Brew** Formulae so users can install **Inshellisense** via **Brew** which is also a package manager.

**Comment by cpendery** [comment] 2023-11-16 20:02
We will be moving to exclusively to binary releases which will make the requirements added in #79 easier to meet and requested in #32. Once those changes are made, I'll start working on a bottle

**Comment by cpendery** [comment] 2024-03-09 21:56
Closing as duplicate of #199

**Closed by cpendery** 2024-03-09 21:56 UTC
Labels: feature-request
