### ISSUE TITLE
Ctrl+a did not activate the prompt function, but only selected the command in PowerShell

### ISSUE THREAD

**Issue by wsurer** [microsoft/inshellisense#72] opened 2023-11-12 15:31 UTC
**Ctrl+a did not activate the prompt function, but only selected the command in PowerShell**

**To Reproduce**
1. execute ```is bind```
2. select powershell and press 'enter'
3. type ```git``` and press Ctrl+a
4. did not activate the prompt function, but only selected the command ```git```

**Expected behavior**
active the prompt function for command ```git```

**Environment**
 - OS: [Windows 10]
 - Output of `inshellisense --version`: 0.0.1-rc.4
 - Nodejs Version: [v16.20.2]

**Additional context**
it worked normally via executing ```is``` and entering the session.
![image](https://github.com/microsoft/inshellisense/assets/140772606/0bf59815-e471-4155-98e3-db2c68d5630d)

**Comment by Muffeter** [comment] 2023-11-15 10:00
Hello [wsurer](https://github.com/wsurer), check your .ps1 config (probably in `C:\Users\<username>\Documents\WindowsPowerShell\`), does the line `if(Test-Path 'C:\Users\<username>\.inshellisense\key-bindings-powershell.ps1' -PathType Leaf){. C:\Users\<username>\.inshellisense\key-bindings-powershell.ps1}` exist in the config? If not you can add the code manually. 

It maybe something wrong happened during binding. In my computer it works well. If this doesn't work, please tell me :)

**Comment by oaustegard** [comment] 2023-11-17 17:22
Same net effect -- When run from a native powershell command, Ctrl+A merely selects the current command, if run from inside inshellisense it simply outputs the letter a

I can confirm the ps1 config file contains the above line and pointing to an existing key-binding-powershell.ps1

Windows 10
Powershell 7.3.8

**Comment by SY-LG** [comment] 2023-12-02 16:13
Same at first. I use Windows 10 with Windows Terminal version 1.18.3181.0 and PowerShell 5.1.19041.3636. Here's how I resolved it:

1. locate oh-my-posh activate command within the ps1 configuration file:
`oh-my-posh init pwsh --config "$env:POSH_THEMES_PATH\capr4n.omp.json" | Invoke-Expression`
2. move it to a position after the inshellisense binding command.

After doing this, the ctrl+a shortcut started working smoothly for me.

I'm not an expert on this, but I suspect that oh-my-posh somehow alters the environment. But looking at @wsurer's screenshot, it doesn't seem like he's using oh-my-posh. Therefore, it might be worth checking for other suspicious commands that could be causing this issue.

**Comment by cpendery** [comment] 2023-12-05 21:58
Closing as this was fixed since we no longer depend on key bindings in [0.0.1-rc.5](https://github.com/microsoft/inshellisense/releases/tag/0.0.1-rc.5)

**Closed by cpendery** 2023-12-05 21:58 UTC
Labels: bug
