### ISSUE TITLE
PowerShell: The 'cd' command does not change directory

### ISSUE THREAD

**Issue by philibertperusse** [microsoft/inshellisense#11] opened 2023-11-06 23:30 UTC
When running inshellisence, doing a 'cd [a_folder]' will not change directory properly even if folder exist.

And using the 'cd' suggestions of "../" will not work either

1. start inshellisense (manually or through the binding)
2. pwd
3. cd ..
4. pwd
6. Directory is the same, should not.

**Comment by lafonj** [comment] 2023-11-07 12:41
This also happens in Linux

**Comment by josharian** [comment] 2023-11-08 22:26
..and zsh on macOS.

**Comment by cpendery** [comment] 2023-11-08 23:59
I think this is a duplicate of #5. I'm working on addressing this issue as I mentioned in #10. Thanks for reporting these!

**Comment by cpendery** [comment] 2023-12-05 21:45
Closing as this was fixed in [0.0.1-rc.5](https://github.com/microsoft/inshellisense/releases/tag/0.0.1-rc.5)

**Closed by cpendery** 2023-12-05 21:45 UTC
Labels: bug
