### ISSUE TITLE
Homebrew installation would be incredibly helpful and increase adoption

### ISSUE THREAD

**Issue by ylluminate** [microsoft/inshellisense#84] opened 2023-11-17 07:28 UTC
Many folks are accustomed to using Homebrew or MacPorts on macOS to install and update apps. Having Inshellisense installable and updated via this would really help adoption and uptake. I know many folks that just don't mess with things anymore unless there's a Homebrew tap or it's on MacPorts.

**Comment by cpendery** [comment] 2023-11-17 09:10
Duplicate of #82

**Comment by cpendery** [comment] 2024-03-09 21:56
Closing as duplicate of #199

**Closed by cpendery** 2024-03-09 21:56 UTC
Labels: feature-request
