### ISSUE TITLE
How to troubleshoot why there are no prompts when entering commands after inshellisense is started

### ISSUE THREAD

**Issue by alanhg** [microsoft/inshellisense#120] opened 2023-12-14 15:01 UTC
**Is your feature request related to a problem? Please describe.**

on my mac, after inshellisense is started，command completion is not show.

I have two Macs that aren't working, and you can see the details in the video.

## my mac 

- Sonoma 14.0
- iTerm2 v3.5.0beta17/ Mac's built-in Terminal Version 2.14 (450)
- ZSH Shell

**Describe the solution you'd like**

doc or cli command

**Additional context**
Add any other context or screens

https://github.com/microsoft/inshellisense/assets/9245110/bbf331e7-d475-48cc-8f1f-9919b8566d19

**Comment by cpendery** [comment] 2023-12-14 22:46
I'll add some troubleshooting documentation. Prompt detection is something I'm working on improving which is most likely your issue

**Comment by alanhg** [comment] 2023-12-15 04:26
> I'll add some troubleshooting documentation. Prompt detection is something I'm working on improving which is most likely your issue

Regarding my question, I found that changing the zsh theme from powerlevel10k/powerlevel9k solved the problem.

**Comment by cpendery** [comment] 2023-12-17 06:42
> > I'll add some troubleshooting documentation. Prompt detection is something I'm working on improving which is most likely your issue
> 
> Regarding my question, I found that changing the zsh theme from powerlevel10k/powerlevel9k solved the problem.

Ah that makes sense, I've handled prompt detection for zsh when using `$PS1`, but I'll need to support more dynamic prompts like powerlevel10k.

**Comment by ipenywis** [comment] 2024-01-05 07:26
@alanhg Did you do anything specific to change the theme. I went through and installed the powerlevel9k theme using brew and then updated the zshrc with `ZSH_THEME="powerlevel9k/powerlevel9k"` but it is still not working.

**Comment by cpendery** [comment] 2024-03-07 00:58
Closing as duplicate of #174

**Closed by cpendery** 2024-03-07 00:58 UTC
Labels: feature-request
