### ISSUE TITLE
Parse error near `__inshellisense

### ISSUE THREAD

**Issue by zhelenskiy** [microsoft/inshellisense#24] opened 2023-11-07 19:28 UTC
**Describe the bug**
The app fails with ``.inshellisense/key-bindings.zsh:10: parse error near `__inshellisense'`` when I open terminal after the installation. 

**To Reproduce**
1. Install the app on Mac M2 Pro
2. Open new terminal
3. Get the message.
4. Inshellisense does not work.

**Expected behavior**
Everything works fine

**Environment**
 - OS: macOS 14.0
 - Output of `inshellisense --version`: 0.0.1-rc.1
 - Nodejs Version: 16.0.0

**Additional context**
```
is -s zsh

  ERROR  pagedSuggestions.at is not a function

 file:///opt/homebrew/lib/node_modules/@microsoft/inshellisense/build/ui/sugges
 tions.js:48:48

 -Suggestion (file:///opt/homebrew/lib/node_modules/@microsoft/inshellisense/bu
            ild/ui/suggestions.js:48:48)
 -renderWithHo (/opt/homebrew/lib/node_modules/@microsoft/inshellisense/node_mo
  ks          dules/react-reconciler/cjs/react-reconciler.development.js:7478:1
              8)
 -mountIndeterminateCo (/opt/homebrew/lib/node_modules/@microsoft/inshellisense
  ponent              /node_modules/react-reconciler/cjs/react-reconciler.devel
                      opment.js:11247:13)
 -beginWor (/opt/homebrew/lib/node_modules/@microsoft/inshellisense/node_module
          s/react-reconciler/cjs/react-reconciler.development.js:12760:16)
 -beginWork$ (/opt/homebrew/lib/node_modules/@microsoft/inshellisense/node_modu
            les/react-reconciler/cjs/react-reconciler.development.js:19569:14)

 -performUnitOfW (/opt/homebrew/lib/node_modules/@microsoft/inshellisense/node_
  rk            modules/react-reconciler/cjs/react-reconciler.development.js:18
                703:12)
 -workLoopSy (/opt/homebrew/lib/node_modules/@microsoft/inshellisense/node_modu
  c         les/react-reconciler/cjs/react-reconciler.development.js:18609:5)
 -renderRootSy (/opt/homebrew/lib/node_modules/@microsoft/inshellisense/node_mo
  c           dules/react-reconciler/cjs/react-reconciler.development.js:18577:
              7)
 -performSyncWorkO (/opt/homebrew/lib/node_modules/@microsoft/inshellisense/nod
  Root            e_modules/react-reconciler/cjs/react-reconciler.development.j
                  s:18193:20)
 -flushSyncCallb (/opt/homebrew/lib/node_modules/@microsoft/inshellisense/node_
  cks           modules/react-reconciler/cjs/react-reconciler.development.js:29
                36:22)

  ERROR  pagedSuggestions.at is not a function

 file:///opt/homebrew/lib/node_modules/@microsoft/inshellisense/build/ui/sugges
 tions.js:48:48

 -Suggestion (file:///opt/homebrew/lib/node_modules/@microsoft/inshellisense/bu
            ild/ui/suggestions.js:48:48)
 -renderWithHo (/opt/homebrew/lib/node_modules/@microsoft/inshellisense/node_mo
  ks          dules/react-reconciler/cjs/react-reconciler.development.js:7478:1
              8)
 -mountIndeterminateCo (/opt/homebrew/lib/node_modules/@microsoft/inshellisense
  ponent              /node_modules/react-reconciler/cjs/react-reconciler.devel
                      opment.js:11247:13)
 -beginWor (/opt/homebrew/lib/node_modules/@microsoft/inshellisense/node_module
          s/react-reconciler/cjs/react-reconciler.development.js:12760:16)
 -beginWork$ (/opt/homebrew/lib/node_modules/@microsoft/inshellisense/node_modu
            les/react-reconciler/cjs/react-reconciler.development.js:19569:14)

 -performUnitOfW (/opt/homebrew/lib/node_modules/@microsoft/inshellisense/node_
  rk            modules/react-reconciler/cjs/react-reconciler.development.js:18
                703:12)
 -workLoopSy (/opt/homebrew/lib/node_modules/@microsoft/inshellisense/node_modu
  c         les/react-reconciler/cjs/react-reconciler.development.js:18609:5)
 -renderRootSy (/opt/homebrew/lib/node_modules/@microsoft/inshellisense/node_mo
  c           dules/react-reconciler/cjs/react-reconciler.development.js:18577:
              7)
 -performSyncWorkO (/opt/homebrew/lib/node_modules/@microsoft/inshellisense/nod
  Root            e_modules/react-reconciler/cjs/react-reconciler.development.j
                  s:18193:20)
 -flushSyncCallb (/opt/homebrew/lib/node_modules/@microsoft/inshellisense/node_
  cks           modules/react-reconciler/cjs/react-reconciler.development.js:29
                36:22)
The above error occurred in the <Suggestions> component:

    at Suggestions (file:///opt/homebrew/lib/node_modules/@microsoft/inshellisense/build/ui/suggestions.js:42:39)
    at ink-box
    at file:///opt/homebrew/lib/node_modules/@microsoft/inshellisense/node_modules/ink/build/components/Box.js:5:27
    at UI (file:///opt/homebrew/lib/node_modules/@microsoft/inshellisense/build/ui/ui-root.js:11:15)
    at App (file:///opt/homebrew/lib/node_modules/@microsoft/inshellisense/node_modules/ink/build/components/App.js:19:9)

React will try to recreate this component tree from scratch using the error boundary you provided, InternalApp.
```

**Comment by cpendery** [comment] 2023-11-07 19:56
This might be a combination of both node version && CRLF issues. See #16 for the parsing error as this is a duplicate of that. Which node version are you using @zhelenskiy?

**Comment by zhelenskiy** [comment] 2023-11-07 23:13
@cpendery mentioned it in the description: 16.0.0.

**Comment by cpendery** [comment] 2023-11-08 16:34
@zhelenskiy, can you try again with `0.0.1-rc.3` once it gets published to npm?

**Comment by zhelenskiy** [comment] 2023-11-08 23:11
The same
<img width="682" alt="image" src="https://github.com/microsoft/inshellisense/assets/55230817/9d94c3be-9433-4d25-a44e-22270f52259b">

**Comment by cpendery** [comment] 2023-11-08 23:57
> The same <img alt="image" width="682" src="https://user-images.githubusercontent.com/55230817/281567546-9d94c3be-9433-4d25-a44e-22270f52259b.png">

@zhelenskiy you try running the `is uninstall` command to clear the key bindings and then create a fresh binding for zsh via `is bind`. It may still have left over CRLFs from the first time you created the binding

**Comment by zhelenskiy** [comment] 2023-11-09 08:50
Ok, now it doesn't show anything in the new terminal, but it also does nothing at all. I use iTerm by the way.

**Comment by cpendery** [comment] 2023-11-09 16:14
Great, so you can start a new inshellisense session by running `^A` or via running `is -s zsh`. It won't start one for you automatically on shell start

**Closed** 2023-11-09 17:07 UTC
Labels: bug

**Comment by zhelenskiy** [comment] 2023-11-09 21:35
<img width="997" alt="image" src="https://github.com/microsoft/inshellisense/assets/55230817/726d4bc6-a370-49ec-8201-c6478620ae37">

**Comment by cpendery** [comment] 2023-11-09 21:39
You'll need at least node 16.6.0 & higher based on [Mozilla's docs](https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/array/at#browser_compatibility) for the `.at` function. This is the same issue as #14.
