### ISSUE TITLE
Does not work with starship prompt

### ISSUE THREAD

**Issue by TuomasAutio** [microsoft/inshellisense#262] opened 2024-05-30 12:56 UTC
**Describe the bug**
When using the inshellisense plugin in conjunction with the [Starship](https://github.com/starship/starship) prompt in a Zsh shell, the inshellisense plugin fails to work as expected. Specifically, it does not give suggestions when starship is active

**To Reproduce**
1. Configure inshellisense in your `.zshrc` file.
2. Install and configure the Starship prompt in the same `.zshrc` file.
3. Open a new terminal session.
4. See that it does not work

**Expected behavior**
Drop down auto suggestions 

**Environment**
 - OS: macOS Sonoma
 - Output of `0.0.1-rc.15 `
 - Nodejs Version: `v22.0.0`
 - Shell: `zsh`
 - Shell Version: `5.9`

**Additional context**
Probably conflicts with the [hooks](https://github.com/starship/starship/blob/master/src/init/starship.zsh) used by the Starship prompt (e.g., precmd and preexec)

**Comment by superdinmc** [comment] 2024-06-01 18:29
This also happens to me,
Without ble.sh:
![image](https://github.com/microsoft/inshellisense/assets/42496449/37fbd4d4-53b0-4ce7-b141-0228799e0c0b)
With ble.sh:
![image](https://github.com/microsoft/inshellisense/assets/42496449/c2246c4d-9d1c-4cbd-b57c-da7962c37b1c)

**Comment by akinomyoga** [comment] 2024-06-01 19:13
Do you think it is related to the right prompt? How about the behavior without the right prompt?

**Comment by superdinmc** [comment] 2024-06-02 03:21
![image](https://github.com/microsoft/inshellisense/assets/42496449/4f806d9a-ea01-4ccc-b607-505e9ffd3247)
Oh yeah, It started working again after I disabled right prompt

**Comment by akinomyoga** [comment] 2024-06-02 03:48
Then, I think inshellisense is confused by the existence of the right prompt. I searched in the repository for "right prompt", but nothing seems to be mentioned, so I think inshellisense doesn't just support shell settings with right prompts for now.

**Comment by cpendery** [comment] 2024-06-03 21:27
I added this original to handle right prompts, which I'd expect to get triggered here. I think there are outstanding issues with zsh that might be contributing this as well (outside of the right prompt issue the bash users are experiencing)
https://github.com/microsoft/inshellisense/blob/1a309c8104ee92d5fff2e16f689db0372796a788/src/isterm/commandManager.ts#L242

**Comment by NireBryce** [comment] 2024-07-06 02:56
@superdinmc how did you get it to play nicely with blesh? blesh seems to override it's bindings.

**Comment by cpendery** [comment] 2024-10-25 02:33
@TuomasAutio, I can't replicate this currently with `0.0.1-rc.15` with zsh `5.8.1` (I am on ubuntu though). My `.zshrc` looks like this

```shell
# ---------------- inshellisense shell plugin ----------------
if [[ -z "${ISTERM}" && $- = *i* && $- != *c* ]]; then
  if [[ -o login ]]; then
    is -s zsh --login ; exit
  else
    is -s zsh ; exit
  fi
fi

# ---------------- startship plugin ----------------
eval "$(starship init zsh)"
```

Can you send your `.zshrc` here along along with the logs at `~/.inshellisense/inshellisense.log` after starting inshellisense and running 1 command with the `-v` flag?

**Comment by cpendery** [comment] 2024-10-25 02:34
> Can you send your `.zshrc` here along along with the logs at `~/.inshellisense/inshellisense.log` after starting inshellisense and running 1 command with the `-v` flag?

Same for you @superdinmc, I'll try to reproduce with `ble.sh` after

**Comment by superdinmc** [comment] 2024-10-25 10:05
It's been months since I tried to use inshellisense on blesh but I will follow-up with the .bashrc ASAP.

**Comment by cpendery** [comment] 2024-10-25 15:24
> It's been months since I tried to use inshellisense on blesh but I will follow-up with the .bashrc ASAP.
> 
> There's also starship configuration, I will also have it here.

Sorry for the long silence on the issues, I haven't been able to work on it for a while. The project should get more attention moving forward

**Comment by superdinmc** [comment] 2024-10-31 01:16
[.bashrc](https://superdin.bot.style/m2wm5x16qfe.bashrc)
[starship.toml](https://superdin.bot.style/starship.toml)

GitHub wouldn't let me upload the files and I lost access to my main domain so I'm using Tixte subdomain temporarily(and cloudflare went down when I tried to set it up with the new domain...).

**Comment by cpendery** [comment] 2024-11-07 03:26
I think this should be fixed in the most recent changes that will be released in `0.0.1-rc.17`. You'll need to run `is doctor` and make any of the changes it recommends, but that should fix any configuration issues. Will reopen if it continues to be an issue in the future

**Closed by cpendery** 2024-11-07 03:26 UTC
Labels: bug

**Comment by akinomyoga** [comment] 2024-11-07 03:49
@cpendery Thank you for taking the time to fix the issue! Does the fix also cover the case with `ble.sh` reported by @superdinmc and @NireBryce (as well as the original case with Starship)?

**Comment by cpendery** [comment] 2024-11-07 04:40
> [@cpendery](https://github.com/cpendery) Thank you for taking the time to fix the issue! Does the fix also cover the case with `ble.sh` reported by [@superdinmc](https://github.com/superdinmc) and [@NireBryce](https://github.com/NireBryce) (as well as the original case with Starship)?

@akinomyoga it should fix it, but please feel free to give it a retry once I do the release. I wasn't able to consistently replicate the behavior so I'm hopeful but not confident that it's fixed

**Comment by akinomyoga** [comment] 2024-11-07 05:43
Thanks! 

> @akinomyoga it should fix it, but please feel free to give it a retry once I do the release. I wasn't able to consistently replicate the behavior so I'm hopeful but not confident that it's fixed

OK, then I'll ask the users @superdinmc and @NireBryce about whether the issue is fixed in their environments. I'm just the author of `ble.sh` and not an Inshellisense user who experienced the issue. I received Issue https://github.com/akinomyoga/ble.sh/issues/464 in my project from @NireBryce so wanted to know the status.
