### ISSUE TITLE
Provide native executable

### ISSUE THREAD

**Issue by matthewadams** [microsoft/inshellisense#32] opened 2023-11-08 12:57 UTC
**Is your feature request related to a problem? Please describe.**
I use `asdf` to manage my `node` versions.  I want to have `inshellisense` available across all of my versions.  As it stands, I have to run `npm install -g @microsoft/inshellisense` for each version of `node` that I install.   It'd be easer if you used `bun` or similar to provide a native executable that I could use independently of my current `node` runtimes.

**Describe the solution you'd like**
I want to be able to run `inshellisense` no matter which version of `node` that is currently on my path.

**Describe alternatives you've considered**
`npx inshellisense`

**Additional context**
None.

**Comment by cpendery** [comment] 2023-11-08 16:32
Hey @matthewadams, I'll look into options to provide this. I'm familiar with [pkg](https://github.com/vercel/pkg), but I'll look into bun's `--compile` flag as well.

**Comment by tnfssc** [comment] 2024-01-31 07:21
@matthewadams @cpendery, I made something like this a while ago. Here's the code to build the binaries [https://github.com/tnfssc/inshellisense-bin](https://github.com/tnfssc/inshellisense-bin)

**Comment by cpendery** [comment] 2024-03-07 23:12
Just a follow up here, most of the projects like `caxa` or `pkg` have been deprecated with Node 21's support of [sea](https://nodejs.org/api/single-executable-applications.html). node-pty; however, only supports Node 18 officially (with Node 16 & 20 making the cut, but not 21). As a result, there isn't a good solution for building a native executable via Node. Bun might work in the future, but for now, node-pty doesn't support Bun (see https://github.com/microsoft/node-pty/issues/632).

**Comment by cpendery** [comment] 2024-03-09 21:56
Closing as duplicate of #199

**Closed by cpendery** 2024-03-09 21:56 UTC
Labels: feature-request

**Comment by cpendery** [comment] 2026-01-22 20:14
The newest release uses a native executable
